image: maxking/mailman-ci-runner

django-1.8:
  script:
  - tox -e django18

django-1.9:
  script:
  - tox -e django19

django-1.10:
  script:
  - tox -e django19

lint:
  script:
  - tox -e lint

docs:
  script:
  - tox -e docs
